AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Zodiac Frontend

  The front-end user interface for tracking packages.

Mappings:
  Resources:
    SourceCodeBucket:
      dev: rac-dev-zodiac-frontend
      prod: rac-prod-zodiac-frontend

Parameters:
  ApplicationEnvironment:
    Type: String
    Description: The environment in which the infrastructure should be deployed.
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !FindInMap [Resources, SourceCodeBucket, !Ref ApplicationEnvironment]
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: zodiac-frontend