name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - base

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    env:
      APPLICATION_NAME: zodiac_frontend
      APPLICATION_PORT: 3000
      AWS_BUCKET_NAME: "${{ github.ref_name == 'development' && 'rac-dev-codedeploy-apps' || 'rac-prod-deploy' }}"
      DEPLOY_ZIP_NAME: zodiac_frontend.zip
      DEPLOYMENT_GROUP: "${{ github.ref_name == 'development' && 'ZodiacFrontendDevelopment' || 'ZodiacFrontendProduction' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Use Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 'lts/*'
      
      - name: Cache dependencies
        uses: actions/cache@v5.0.4
        id: yarn-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}More actions
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Export secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1.8
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Clone deploy scripts
        run: git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git;

      - name: Substitute environment variables
        uses: tvarohohlavy/inplace-envsubst-action@v1.0.0
        with:
          files: |
            .env.deploy
            appspec.yml.deploy
            deploy_scripts/curl_index.sh.deploy
            deploy_scripts/stop_nextjs.sh.deploy
            deploy_scripts/restart_nextjs.sh.deploy
            deploy_scripts/set_permissions.sh.deploy
      
      - name: Rename deploy files
        run: |
          mv .env.deploy .env
          mv appspec.yml.deploy appspec.yml
          mv deploy_scripts/curl_index.sh.deploy deploy_scripts/curl_index.sh
          mv deploy_scripts/stop_nextjs.sh.deploy deploy_scripts/stop_nextjs.sh
          mv deploy_scripts/restart_nextjs.sh.deploy deploy_scripts/restart_nextjs.sh
          mv deploy_scripts/set_permissions.sh.deploy deploy_scripts/set_permissions.sh

      - name: Build applicationMore actions
        run: yarn run build

      - name: Make zip file
        run: zip -r ${{ env.DEPLOY_ZIP_NAME }} . -x .git/\*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 cp ${{ env.DEPLOY_ZIP_NAME }}  s3://${{ env.AWS_BUCKET_NAME }}

      - name: Deploy to AWS CodeDeploy
        run: aws deploy create-deployment
          --region ${{ secrets.AWS_REGION }}
          --application-name ${{ env.APPLICATION_NAME }}
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP }}
          --s3-location bucket=${{ env.AWS_BUCKET_NAME }},bundleType=zip,key=${{ env.DEPLOY_ZIP_NAME }}
